### ISSUE TITLE
Percentile filter

### ISSUE THREAD

**Issue by Xeite** [BrunoBonacci/hdr-plot#1]
Hi, thank you for great tool. 

Is there any way to filter out high percentiles?

Due to the high value for tail percentiles (99.9, 99.99....), I hardly see normal values. So if I can get a functionality to skip such an extreme case, I think it's more valuable as visualizer.

I'm not familiar with pandas/matplot, but if you give me some hint I will happily change it on my own.

Thanks :)

**Comment by BrunoBonacci** [comment]
Hi,

`hdr-plot` is specifically designed to capture details in the tail. Hence the use of HDR histograms.
because of that I never found the need for it....

For example here the three lines hardly differ from each other until the far end of the tail.
![myplot.png](https://github.com/BrunoBonacci/hdr-plot/raw/master/myplot.png)

I will have to look into it, but as a workaround, you can use this online-plotter which supports the tail truncation
https://hdrhistogram.github.io/HdrHistogram/plotFiles.html
